wayland-internal-vsync=yes
vo=gpu-next
hwdec=auto-safe

save-position-on-quit=yes
keep-open=yes
autofit-larger=90%x90%
cursor-autohide=500

no-border
osd-font='Inter'
osc=no
osd-bar=no

video-sync=display-resample
interpolation=yes
tscale=oversample

glsl-shaders="~/.config/mpv/shaders/ArtCNN_C4F16.glsl"
